name: Simple Usage

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Hiero Solo
        uses: ./
        id: solo

      - name: Validate Hiero Solo Outputs
        run: |
          if [ -z "${{ steps.solo.outputs.accountId }}" ]; then
            echo "Account ID is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.privateKey }}" ]; then
            echo "Private Key is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.publicKey }}" ]; then
            echo "Public Key is missing!"
            exit 1
          fi
          echo "All outputs are valid."
